Repository CECOM-CAU/CECOM_Web_Admin, pull requests merged in 2024-09, with the labels that each got.

#3 [DOC] Convention 문서 작성
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  Convention.md
Labels: doc

#4 [DEV] Tailwind 스타일링 설정
  src/app/globals.css
  src/fonts/GmarketSansBold.otf
  src/fonts/GmarketSansLight.otf
  src/fonts/GmarketSansMedium.otf
  tailwind.config.ts
Labels: dev

#7 [FIX] Admin 빌드 이슈 해결
  next.config.mjs
Labels: fix

#9 [DEV] Admin Route 설정
  src/app/activity/page.tsx
  src/app/main/page.tsx
  src/app/member/page.tsx
  src/app/notice/page.tsx
  src/app/recruit/page.tsx
Labels: dev

#11 [FIX] Admin Route 빌드 이슈 해결
  src/app/activity/page.tsx
  src/app/layout.tsx
  src/app/main/page.tsx
  src/app/member/page.tsx
  src/app/notice/page.tsx
  src/app/page.tsx
  src/app/recruit/page.tsx
Labels: fix

#13 [DEV] Admin recruit basic UI
  src/app/layout.tsx
  src/app/page.tsx
  src/app/recruit/_component/ApplicationModal.tsx
  src/app/recruit/_component/Item.tsx
  src/app/recruit/_component/LongItem.tsx
  src/app/recruit/page.tsx
Labels: dev

#15 [FIX] 커밋 이슈 해결
  src/app/recruit/_component/ApplicationModal.tsx
Labels: fix

#18 [DEV] Admin API 라우팅 설정
  src/app/api/activity/delActivityItem/[id]/route.ts
  src/app/api/activity/getActivityList/[id]/route.ts
  src/app/api/activity/postActivityItem/route.ts
  src/app/api/main/postImage/[id]/route.ts
  src/app/api/member/delMemberItem/[id]/route.ts
  src/app/api/member/getMemberList/route.ts
  src/app/api/member/postMemberItem/route.ts
  src/app/api/notice/delNoticeItem/[id]/route.ts
  src/app/api/notice/getNoticeList/route.ts
  src/app/api/notice/postNoticeItem/route.ts
  src/app/api/recruit/getSubmissionDetail/[id]/route.ts
  src/app/api/recruit/getSubmissionList/route.ts
Labels: dev

#21 [DEV] recruit 페이지 기능 추가
  package.json
  src/app/recruit/_component/ApplicationModal.tsx
  src/app/recruit/_component/Item.tsx
  src/app/recruit/_component/LongItem.tsx
  src/app/recruit/page.tsx
Labels: dev

#23 [DEV] Admin Firebase 설정 및 Login API 구현
  .gitignore
  package-lock.json
  package.json
  src/app/api/login/tryLogin/route.ts
  src/util/CorsUtil.ts
  src/util/FirebaseUtil.ts
  src/util/Interface.ts
Labels: dev

#25 [FIX] Admin Login API 이슈 해결
  src/util/FirebaseUtil.ts
  src/util/Interface.ts
Labels: fix

#31 [DEV] Admin Question API 추가 구현
  src/app/api/recruit/getAvailability/route.ts
  src/app/api/recruit/getQuestionList/route.ts
  src/util/FirebaseUtil.ts
  src/util/Interface.ts
Labels: dev

#33 [DEV] recruit 페이지 지원자 정보 불러오기
  src/app/login/page.tsx
  src/app/recruit/_component/ApplicationModal.tsx
  src/app/recruit/_component/LongItem.tsx
  src/app/recruit/page.tsx
Labels: dev
